services:
  postgres:
    image: postgres
    container_name: twitter-clone
    environment:
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: twitter
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_twitter
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgresql
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge


volumes:
  pgadmin:
  postgres: